version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: revezai_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: revezai
    ports:
      - "5432:5432"